
// Objective-C API for talking to the following Go packages
//
//	gw/pkg/asdk
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Asdk_FRAMEWORK_H__
#define __Asdk_FRAMEWORK_H__

#include "Asdk.objc.h"
#include "Universe.objc.h"

#endif
